### ISSUE TITLE
grass turning into dirt just by putting on shoes 

### ISSUE THREAD

**Issue by lostopkk** [pcal43/trailblazer#18]
fabric 0.15.3 - minecraft version: 1.20.1

I understand that there is a mechanic if you wear clothes the ground turns into a path sooner, but it's not very "instant"? It seems like something that isn't realistic and ends up screwing up a lot

https://github.com/pcal43/trailblazer/assets/50776714/d43c479b-3ca2-44cd-aecd-d3e09b11ca72

**Comment by pcal43** [comment]
this is all configurable - see the docs/config file.

**Comment by lostopkk** [comment]
> this is all configurable - see the docs/config file.

I know everything can be configured, but do you want your mod to continue this way by default? imagine every time someone uses your mod they have to configure it and the way it is the mod is very strange, at least for me.

**Comment by pcal43** [comment]
i gess my thinkng was that if the effect were too subtle, people wouldnt understand what the mod is doing 🤷

**Comment by lostopkk** [comment]
> i gess my thinkng was that if the effect were too subtle, people wouldnt understand what the mod is doing 🤷 

sorry if it seemed rude, I just wanted to say that in a way the mod is already passive, so it would be more interesting to take more time for the person to think "damn, do we walk around this place that much?", if you put it instantly, the People only think that it only happened a few times and the dirt has already been transformed.  Everything is a matter of opinion, how my world was going instantly with this mod became very strange because wherever we passed it left the world more polluted than beautiful.

**Comment by pcal43** [comment]
all good.  i made it configurable so people can make it work however they want.  cheers.
